### PR TITLE
Add support for WordPress coding standard

### PR DESCRIPTION
**Pull request by sudar**
I have added support for formatting php code according to [WordPress PHP coding standard](https://make.wordpress.org/core/handbook/coding-standards/php/).

I have disabled it by default so as to not interfere with existing code.

Would appreciate if you can merge it. Thanks.

### CODE REVIEW

**Comment by cmrcx** [comment]
Thank you!

My merge commits look a bit weird, because the main repository for this project is in subversion and this was the first time I did a merge through the git-svn bridge.

**Comment by sudar** [comment]
Thanks for merging it and sorry for the whitespace and formatting issues. I was trying to match the formatting that you were using as closely as possible but still have missed out some.

I am currently working on creating a vim plugin to format code for WordPress/PHP files using your phptidy. Would you be interested in a couple of more pull requests? In short I am planning to make the following changes while maintaining backward compatibility as much as possible.
- Wrap all echo statements with a verbose flag
- A new command to output the formatted code instead of writing it to a file. I need this for Vim integration
- Ability to pass config parameters as part of command line in addition to passing them through a config file.
- A homebrew package for phptidy.

**Comment by cmrcx** [comment]
That sounds very good.
Instead of a verbose flag I would prefer a quiet flag. Because on command line you would probably always at least want to know if phptidy changed anything.

**Comment by sudar** [comment]
> Instead of a verbose flag I would prefer a quiet flag. Because on command line you would probably always at least want to know if phptidy changed anything.

Sure. I will use a quiet flag.

Will keep sending you pull requests as I complete them.

**Pull request merged**
